# Generated by Django 4.1.3 on 2022-11-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='banc',
            new_name='Band',
        ),
    ]
