# Generated by Django 4.1.3 on 2022-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_description_listing_sold_listing_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('R', 'Records'), ('C', 'Clothong'), ('M', 'Miscellaneous')], default='M', max_length=50),
            preserve_default=False,
        ),
    ]
